In [2]:
import numpy as np

In [4]:
l = [1,2,3,4] #Python List
a = np.array([1,2,3,4]) #Numpy Array

print(l,type(l))
print(a,type(a))

[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>


In [10]:
print(a+1) #Broadcasting

[2 3 4 5]


In [11]:
# Square all elements of the array
print(a**2)

[ 1  4  9 16]


In [12]:
b = np.array([[1,2,3],
              [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
b.shape

(2, 3)

In [17]:
b = b.reshape((6,1))
print(b)
print(b[0][0])

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
1


In [18]:
b = b.reshape((6,))
print(b)
print(b[0])

[1 2 3 4 5 6]
1


In [20]:
b = b.reshape((3,2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [31]:
a = np.zeros((5,4),dtype='int')
a[1:4,1:3] = 5
a[ : , -1] = 7
print(a)
#print(a.dtype)

[[0 0 0 7]
 [0 5 5 7]
 [0 5 5 7]
 [0 5 5 7]
 [0 0 0 7]]


In [36]:
b = np.ones((5,4),dtype='int')*9 
print(b)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [38]:
c = np.vstack((a,b))
print(c)
print(c.shape)

[[0 0 0 7]
 [0 5 5 7]
 [0 5 5 7]
 [0 5 5 7]
 [0 0 0 7]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
(10, 4)


In [39]:
d = np.hstack((a,b))
print(d)
print(d.shape)

[[0 0 0 7 9 9 9 9]
 [0 5 5 7 9 9 9 9]
 [0 5 5 7 9 9 9 9]
 [0 5 5 7 9 9 9 9]
 [0 0 0 7 9 9 9 9]]
(5, 8)


In [41]:
# Transpose
d.T

array([[0, 0, 0, 0, 0],
       [0, 5, 5, 5, 0],
       [0, 5, 5, 5, 0],
       [7, 7, 7, 7, 7],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [44]:
I = np.eye(5,dtype='int')
print(I)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [45]:
arr = np.array([39,56,23,12])

In [48]:
print(arr.max())
print(arr.min())
print(arr.argmax())
print(arr.argmin())

56
12
1
3


In [49]:
arr.mean()

32.5

In [50]:
arr.std()

16.62077013859466

### Random Numbers

In [83]:
no = np.round(np.random.random())*5 + 8

In [84]:
no

13.0

In [134]:
np.random.randint(10,100,size=(4,3))

array([[62, 75, 27],
       [19, 93, 18],
       [85, 65, 58],
       [39, 59, 93]])

In [135]:
arr = np.random.randn(10,10)*5 + 10

In [136]:
arr[:3]

array([[ 6.19910057, 11.78525021, 10.93482362,  2.43869591, 13.94425482,
        14.15199188, 10.14427113, 10.86292033, -1.38274011, 10.62768258],
       [ 9.73137181,  8.02956672, 18.03835361, 19.55702481, 16.68027622,
        11.23651811,  9.12165089, 12.59160088, 15.40047446, 10.13191091],
       [ 7.35555374,  4.32991063,  7.43351938,  9.27740632, 17.66209643,
        20.33431003, 11.66400721, 13.50373019, -3.90717236, 10.36684166]])

In [137]:
arr.mean()

10.22488826530329

In [138]:
arr.std()

4.751944096196439

In [130]:
arr.shape

(10, 10)

In [132]:
arr= arr.reshape(25,-1)

In [145]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([[1,
                  2,
                  3]]).reshape(3,1)

In [146]:
arr1.shape

(2, 3)

In [147]:
arr2.shape

(3, 1)

In [148]:
np.dot(arr1, arr2)

array([[14],
       [32]])

In [150]:
arr1 = np.array([1,2,3,4])

In [151]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [152]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [155]:
arr1 = np.random.randint(0,100,size= (5,5))

In [158]:
arr1

array([[87, 17,  5, 34, 51],
       [ 4, 24,  5, 17, 12],
       [50, 55,  4,  9, 91],
       [60, 87, 86, 67, 54],
       [19, 79,  6, 63, 47]])

In [157]:
np.linalg.inv(arr1)

array([[ 0.03182909,  0.41342519, -0.00547298, -0.01804405, -0.10876522],
       [ 0.0249845 ,  0.65808821, -0.00091362, -0.02846196, -0.16066347],
       [-0.01531918, -0.20276268,  0.00199621,  0.02143015,  0.03990527],
       [-0.01690744, -0.508571  , -0.00883373,  0.02112269,  0.14102926],
       [-0.0302435 , -0.56569144,  0.01533425,  0.02408555,  0.14116338]])